
DROP TABLE IF EXISTS empleados CASCADE;
DROP TABLE IF EXISTS codigo CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS alineacion CASCADE;

CREATE TABLE IF NOT EXISTS empleados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellidos VARCHAR(50) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    fecha_incorporacion DATE NOT NULL,
    salario DOUBLE NOT NULL,
    pais VARCHAR(50) NOT NULL,
    rol VARCHAR(20) NOT NULL,
    especialidad VARCHAR(20),
    posicion VARCHAR(20),
    dorsal INT,
    altura DOUBLE,
    peso DOUBLE,
    goles INT,
    partidos_jugados INT,
    minutos_jugados INT,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    imagen VARCHAR(400) NOT NULL
    );

CREATE TABLE IF NOT EXISTS users (
    nombre_usuario VARCHAR(50) UNIQUE NOT NULL,
    contraseña VARCHAR(255) NOT NULL,
    admin BOOLEAN NOT NULL
);
CREATE TABLE IF NOT EXISTS alineacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_creacion TIMESTAMP NOT NULL,
    fecha_actualizacion TIMESTAMP NOT NULL,
    fecha_juego DATE NOT NULL

);

CREATE TABLE IF NOT EXISTS codigo (
    uuid VARCHAR NOT NULL PRIMARY KEY,
    id_persona BIGINT NOT NULL,
    id_alineacion BIGINT NOT NULL,
    posicion INT NOT NULL
);



